storage_get_upload_url:
  handler: lambdas/storage/get_upload_url.lambda_handler
  events:
    - http:
        cors:
          origin: '*' 
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId:
            Ref: ApiAuthorizer            
        path: /storage/uploadUrl
        method: get
