service: my-api

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: dev
  environment:
    user_pool_id: us-east-1_l6aW4OJ2m
    client_id: 2a64v33th06gk4kskknmjua07s
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminInitiateAuth
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminSetUserPassword
      Resource: "*"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          authorizer:
            name: cognito-authorizer
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:us-east-1:829092859139:userpool/us-east-1_l6aW4OJ2m

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
