Resources:
  LibraryTable:
    DeletionPolicy: Retain
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: library_dev
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI_1
          AttributeType: S
        - AttributeName: GSI_2
          AttributeType: S            
        - AttributeName: GSI_3
          AttributeType: S
        - AttributeName: GSI_4
          AttributeType: S
        - AttributeName: GSI_5
          AttributeType: S           
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI_1
          KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: GSI_1
              KeyType: RANGE
          Projection:
            ProjectionType: 'ALL'

        - IndexName: GSI_2
          KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: GSI_2
              KeyType: RANGE
          Projection:
            ProjectionType: 'ALL'     

        - IndexName: GSI_3
          KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: GSI_3
              KeyType: RANGE
          Projection:
            ProjectionType: 'ALL'

        - IndexName: GSI_4
          KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: GSI_4
              KeyType: RANGE
          Projection:
            ProjectionType: 'ALL'

        - IndexName: GSI_5
          KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: GSI_5
              KeyType: RANGE
          Projection:
            ProjectionType: 'ALL'
      BillingMode: PAY_PER_REQUEST
